// Autogenerated from Pigeon (v18.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.example.install_app_in_app_store

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  return if (exception is FlutterError) {
    listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** Generated class from Pigeon that represents data sent in messages. */
data class AppInstallConfig (
  val iosAppId: Long? = null,
  val iosIapId: String? = null,
  val iosAffiliateToken: String? = null,
  val iosCampaignToken: String? = null,
  val iosAdvertisingPartnerToken: String? = null,
  val iosProviderToken: String? = null,
  val androidPackageName: String? = null,
  val url: String? = null

) {
  companion object {
    @Suppress("LocalVariableName")
    fun fromList(__pigeon_list: List<Any?>): AppInstallConfig {
      val iosAppId = __pigeon_list[0].let { num -> if (num is Int) num.toLong() else num as Long? }
      val iosIapId = __pigeon_list[1] as String?
      val iosAffiliateToken = __pigeon_list[2] as String?
      val iosCampaignToken = __pigeon_list[3] as String?
      val iosAdvertisingPartnerToken = __pigeon_list[4] as String?
      val iosProviderToken = __pigeon_list[5] as String?
      val androidPackageName = __pigeon_list[6] as String?
      val url = __pigeon_list[7] as String?
      return AppInstallConfig(iosAppId, iosIapId, iosAffiliateToken, iosCampaignToken, iosAdvertisingPartnerToken, iosProviderToken, androidPackageName, url)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      iosAppId,
      iosIapId,
      iosAffiliateToken,
      iosCampaignToken,
      iosAdvertisingPartnerToken,
      iosProviderToken,
      androidPackageName,
      url,
    )
  }
}

private object AppInstallApiCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      128.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AppInstallConfig.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is AppInstallConfig -> {
        stream.write(128)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface AppInstallApi {
  fun installApp(config: AppInstallConfig, callback: (Result<Boolean>) -> Unit)

  companion object {
    /** The codec used by AppInstallApi. */
    val codec: MessageCodec<Any?> by lazy {
      AppInstallApiCodec
    }
    /** Sets up an instance of `AppInstallApi` to handle messages through the `binaryMessenger`. */
    fun setUp(binaryMessenger: BinaryMessenger, api: AppInstallApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.install_app_in_app_store.AppInstallApi.installApp$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val configArg = args[0] as AppInstallConfig
            api.installApp(configArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
