// Autogenerated from Pigeon (v18.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

/// Generated class from Pigeon that represents data sent in messages.
struct AppInstallConfig {
  var iosAppId: Int64? = nil
  var iosIapId: String? = nil
  var iosAffiliateToken: String? = nil
  var iosCampaignToken: String? = nil
  var iosAdvertisingPartnerToken: String? = nil
  var iosProviderToken: String? = nil
  var androidPackageName: String? = nil
  var url: String? = nil

  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ __pigeon_list: [Any?]) -> AppInstallConfig? {
    let iosAppId: Int64? = isNullish(__pigeon_list[0]) ? nil : (__pigeon_list[0] is Int64? ? __pigeon_list[0] as! Int64? : Int64(__pigeon_list[0] as! Int32))
    let iosIapId: String? = nilOrValue(__pigeon_list[1])
    let iosAffiliateToken: String? = nilOrValue(__pigeon_list[2])
    let iosCampaignToken: String? = nilOrValue(__pigeon_list[3])
    let iosAdvertisingPartnerToken: String? = nilOrValue(__pigeon_list[4])
    let iosProviderToken: String? = nilOrValue(__pigeon_list[5])
    let androidPackageName: String? = nilOrValue(__pigeon_list[6])
    let url: String? = nilOrValue(__pigeon_list[7])

    return AppInstallConfig(
      iosAppId: iosAppId,
      iosIapId: iosIapId,
      iosAffiliateToken: iosAffiliateToken,
      iosCampaignToken: iosCampaignToken,
      iosAdvertisingPartnerToken: iosAdvertisingPartnerToken,
      iosProviderToken: iosProviderToken,
      androidPackageName: androidPackageName,
      url: url
    )
  }
  func toList() -> [Any?] {
    return [
      iosAppId,
      iosIapId,
      iosAffiliateToken,
      iosCampaignToken,
      iosAdvertisingPartnerToken,
      iosProviderToken,
      androidPackageName,
      url,
    ]
  }
}

private class AppInstallApiCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 128:
      return AppInstallConfig.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class AppInstallApiCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? AppInstallConfig {
      super.writeByte(128)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class AppInstallApiCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return AppInstallApiCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return AppInstallApiCodecWriter(data: data)
  }
}

class AppInstallApiCodec: FlutterStandardMessageCodec {
  static let shared = AppInstallApiCodec(readerWriter: AppInstallApiCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol AppInstallApi {
  func installApp(config: AppInstallConfig, completion: @escaping (Result<Bool, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class AppInstallApiSetup {
  /// The codec used by AppInstallApi.
  static var codec: FlutterStandardMessageCodec { AppInstallApiCodec.shared }
  /// Sets up an instance of `AppInstallApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: AppInstallApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let installAppChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.install_app_in_app_store.AppInstallApi.installApp\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      installAppChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let configArg = args[0] as! AppInstallConfig
        api.installApp(config: configArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      installAppChannel.setMessageHandler(nil)
    }
  }
}
